rules:
  - pattern: 'kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value'
    name: kafka_server_$1_$2
    labels:
      clientId: "$3"
      topic: "$4"
      partition: "$5"
  - pattern: 'java.lang<type=Memory><HeapMemoryUsage>(.+):'
    name: java_memory_heap_$1
